CREATE SEQUENCE IF NOT EXISTS app_users_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cart_items_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS carts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS categories_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS order_items_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS orders_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS products_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS vendors_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE app_users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_non_locked BOOLEAN                                 NOT NULL,
    city               VARCHAR(50),
    country            VARCHAR(50),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    enabled            BOOLEAN                                 NOT NULL,
    failed_attempt     INTEGER,
    first_name         VARCHAR(50)                             NOT NULL,
    last_login_date    TIMESTAMP WITHOUT TIME ZONE,
    last_name          VARCHAR(50)                             NOT NULL,
    lock_time          TIMESTAMP WITHOUT TIME ZONE,
    password           VARCHAR(60)                             NOT NULL,
    phone_number       VARCHAR(15),
    state              VARCHAR(50),
    street             VARCHAR(100),
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    version            BIGINT,
    zip_code           VARCHAR(10),
    CONSTRAINT app_users_pkey PRIMARY KEY (id)
);

CREATE TABLE cart_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    quantity    INTEGER,
    cart_id     BIGINT,
    product_id  BIGINT,
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT,
    CONSTRAINT carts_pkey PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR(500),
    image_url   VARCHAR(255),
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    price      numeric(10, 2)                          NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    payment_method   VARCHAR(30)                             NOT NULL,
    shipping_address VARCHAR(500)                            NOT NULL,
    status           VARCHAR(20)                             NOT NULL,
    total_price      numeric(12, 2)                          NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id          BIGINT                                  NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE products
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active         BOOLEAN                                 NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    description    VARCHAR(1024),
    image_url      VARCHAR(255),
    name           VARCHAR(100)                            NOT NULL,
    price          numeric(10, 2)                          NOT NULL,
    stock_quantity INTEGER                                 NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    category_id    BIGINT                                  NOT NULL,
    seller_id      BIGINT                                  NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE vendors
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address           VARCHAR(255),
    contact_email     VARCHAR(100),
    contact_phone     VARCHAR(20),
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    store_description VARCHAR(1024),
    store_name        VARCHAR(100)                            NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    user_id           BIGINT                                  NOT NULL,
    CONSTRAINT vendors_pkey PRIMARY KEY (id)
);

ALTER TABLE app_users
    ADD CONSTRAINT uk4vj92ux8a2eehds1mdvmks473 UNIQUE (email);

ALTER TABLE carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);

ALTER TABLE vendors
    ADD CONSTRAINT uki4fsfxe266yl9oye02ongwl8 UNIQUE (user_id);

ALTER TABLE vendors
    ADD CONSTRAINT ukklv33bcks43oiq2xe01dmv87t UNIQUE (store_name);

ALTER TABLE products
    ADD CONSTRAINT uko61fmio5yukmmiqgnxf8pnavn UNIQUE (name);

ALTER TABLE categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);

ALTER TABLE cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION;

ALTER TABLE vendors
    ADD CONSTRAINT fk7xprxqauf826m7nivfqwy2ea0 FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE NO ACTION;

ALTER TABLE carts
    ADD CONSTRAINT fk98l14q9u9ji7alu1mlbylmvm8 FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE NO ACTION;

ALTER TABLE products
    ADD CONSTRAINT fk_product_seller FOREIGN KEY (seller_id) REFERENCES app_users (id) ON DELETE NO ACTION;

CREATE INDEX idx_products_seller_id ON products (seller_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fkaf154i5th4vvgbahf8b8pa688 FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE NO ACTION;

ALTER TABLE order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE NO ACTION;

ALTER TABLE order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION;

ALTER TABLE products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE NO ACTION;

ALTER TABLE cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE NO ACTION;

ALTER TABLE orders
    ADD CONSTRAINT fkrg873cdvpd23vrtmqygifcdwa FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE NO ACTION;